# Generated by Django 4.2.11 on 2024-04-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_buyer_role_seller_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='role',
        ),
    ]
