# Generated by Django 5.0.4 on 2024-04-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_listing_purchase_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buyer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Return_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buyer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seller')),
            ],
        ),
    ]
